import { useState } from "react";
import { Image, Pressable, ScrollView, StyleSheet, Text, View } from "react-native";
import { Ionicons } from "@expo/vector-icons";
import { AppButton } from "./AppButton";
import { AppInput } from "./AppInput";
import { useTheme } from "../contexts/ThemeContext";
import { UpdateProfilePayload, User } from "../types";
interface ProfileScreenProps { user: User; onLogout: () => void; onUpdateProfile: (payload: UpdateProfilePayload) => Promise<void>; loading: boolean; feedback: string; }
export function ProfileScreen({ user, onLogout, onUpdateProfile, loading, feedback }: ProfileScreenProps) {
  const { theme, isDark, toggleTheme } = useTheme();
  const [editing, setEditing] = useState(false);
  const [username, setUsername] = useState(user.username);
  const [bio, setBio] = useState(user.bio);
  const avatarSource = user.profile_image_base64 ? { uri: user.profile_image_base64 } : require("../../assets/images/cursify.jpg");
  const handleSave = async () => { await onUpdateProfile({ username: username.trim(), bio: bio.trim(), profile_image_base64: user.profile_image_base64 }); setEditing(false); };
  return <ScrollView style={[styles.container, { backgroundColor: theme.colors.background }]} contentContainerStyle={{ paddingHorizontal: theme.spacing.l, paddingTop: theme.spacing.l, paddingBottom: theme.spacing.xxl }}><Text style={{ fontSize: theme.typography.h2, fontWeight: "700", color: theme.colors.textMain, marginBottom: theme.spacing.l }}>Seu perfil</Text><View style={{ borderRadius: theme.radius.lg, borderWidth: 1, borderColor: theme.colors.border, backgroundColor: theme.colors.surface, padding: theme.spacing.l, alignItems: "center", marginBottom: theme.spacing.l }}><Image source={avatarSource} style={[styles.avatar, { backgroundColor: theme.colors.surfaceHighlight, marginBottom: theme.spacing.m }]} />{editing ? <><AppInput label="Username" value={username} onChangeText={setUsername} testID="profile-username" /><AppInput label="Biografia" value={bio} onChangeText={setBio} testID="profile-bio" /><View style={[styles.row, { gap: theme.spacing.s }]}><AppButton label="Salvar" onPress={handleSave} loading={loading} style={styles.half} testID="profile-save" /><AppButton label="Cancelar" variant="outline" onPress={() => setEditing(false)} style={styles.half} testID="profile-cancel" /></View></> : <><Text style={{ fontSize: 22, color: theme.colors.textMain, fontWeight: "700" }}>{user.username}</Text><Text style={{ marginTop: 2, color: theme.colors.textMuted, fontSize: theme.typography.small }}>@{user.username}</Text><Text style={{ marginTop: theme.spacing.s, color: theme.colors.textMuted, fontSize: theme.typography.small }}>{user.email}</Text><Text style={{ marginTop: theme.spacing.s, color: theme.colors.textMuted, fontSize: theme.typography.small }}>Perfil: {user.role}</Text><Text style={{ marginTop: theme.spacing.m, color: theme.colors.textMain, fontSize: theme.typography.body, width: "100%" }}>{user.bio || "Sem bio informada."}</Text><AppButton label="Editar perfil" variant="secondary" onPress={() => setEditing(true)} style={styles.editBtn} testID="profile-edit" /></>}</View><View style={[styles.row, { borderRadius: theme.radius.lg, borderWidth: 1, borderColor: theme.colors.border, backgroundColor: theme.colors.surface, padding: theme.spacing.m, marginBottom: theme.spacing.l, justifyContent: "space-between", alignItems: "center" }]}><Text style={{ color: theme.colors.textMain, fontSize: theme.typography.body }}>Tema escuro</Text><Pressable onPress={toggleTheme} accessibilityLabel="Alternar tema" style={{ padding: 8 }}><Ionicons name={isDark ? "sunny-outline" : "moon-outline"} size={22} color={theme.colors.textMuted} /></Pressable></View>{feedback ? <Text style={{ marginBottom: theme.spacing.m, color: theme.colors.primary, fontSize: theme.typography.small }}>{feedback}</Text> : null}<AppButton label="Sair da conta" variant="outline" onPress={onLogout} testID="logout-button" /></ScrollView>;
}
const styles = StyleSheet.create({ container: { flex: 1 }, avatar: { width: 84, height: 84, borderRadius: 42 }, row: { flexDirection: "row", marginTop: 8, width: "100%" }, half: { flex: 1 }, editBtn: { marginTop: 16, alignSelf: "stretch" } });

